Converter/Controllers/PdfController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Xml;
using System.IO;
using System.Net;
using System.Threading;
using System.Text;
using System.Text.RegularExpressions;
using System.Diagnostics;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;

namespace Converter.Controllers
{
    public class PdfController : Controller
    {
       
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }       

        [HttpPost]
        public FileResult HtmltoPDF()
        {
           
            string fileName = HttpContext.Request.Form["fileName"];
            string url = HttpContext.Request.Form["pageUrl"];
            string page_sizeX = HttpContext.Request.Form["sizeX"];
            string page_sizeY = HttpContext.Request.Form["sizeY"];
            string page_format = HttpContext.Request.Form["pageFormat"];
            string page_orientation = HttpContext.Request.Form["pageOrientation"];
            string script = "printpdf.js";
            string cmd = ("phantomjs.exe " + script);            
            System.Diagnostics.Process process = new System.Diagnostics.Process();
            process.StartInfo.FileName = "phantomjs.exe";
            process.StartInfo.WorkingDirectory = @"E:\eVeliko\Work\Project_PDF_Converter\PDF_PhantomJS\Converter\Converter\bin\Debug\netcoreapp1.1";            
            process.StartInfo.Arguments = string.Format("{0} {1} {2} {3} {4} {5} {6} ", script, url, fileName, page_sizeX, page_sizeY, page_format, page_orientation);
            process.StartInfo.CreateNoWindow = false;
            process.StartInfo.UseShellExecute = false;
            process.Start();
            process.WaitForExit();
            var result = process.ExitCode;
            var path = string.Format(@"E:\eVeliko\Work\Project_PDF_Converter\PDF_PhantomJS\Converter\Converter\bin\Debug\netcoreapp1.1\{0}", fileName);
            return PhysicalFile(path, "application/pdf");          
           
        }        

    }
}

Converter/Views/Pdf/Index.cshtml
@{
    ViewData["Title"] = "PDF Generator";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="pull-left">
                <h1>
                    HTML to PDF Converter
                   
                </h1>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>

   

    <div class="row">  

            <form asp-action="HtmltoPDF"
                  asp-controller="Pdf" method="post">
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="firstName">Url :</label>
                        <input class="form-control" type="text" name="pageUrl" placeholder="Your url goes here" style="width:100%;" />
                    </div>
                    <div class="form-group">
                        <label for="lastName">File Name :</label>
                        <input class="form-control" type="text" name="fileName" placeholder="Your filename goes here" style="width:100%;" />
                    </div>
                    <button class="btn btn-large btn-info" type="submit">Generate PDF Document</button>
                    </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="firstName">Web Page Width:</label>
                        <input class="form-control" type="text" name="sizeX" placeholder="1600" style="width:100%;" />
                        </div>
                        <div class="form-group">
                            <label for="lastName">
                                Web Page Height:
                            </label>
                            <input class="form-control" type="text"  name="sizeY" placeholder="1200" style="width:100%;" />

                        </div>
                  </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <label>Pdf Page Size:</label>
                        <select class="form-control" name="pageFormat">
                            <option value="A1">A1</option>
                            <option value="A2">A2</option>
                            <option value="A3">A3</option>
                            <option value="A4" selected>A4</option>
                            <option value="A5">A5</option>
                            <option value="Letter">Letter</option>
                            <option value="Tabloid">Tabloid</option>
                            <option value="Ledger">Ledger</option>
                            <option value="Legal">Legal</option>
                        </select>
                        </div>
                    <div class="form-group">
                        <label>Pdf Page Orientation:</label>
                        <select class="form-control" name="pageOrientation">
                            <option value="portrait" selected>Portrait</option>
                            <option value="landscape">Landscape</option>
                        </select><br />
                        <br />
                        </div>
                    </div>

</form>
        
        </div>


</div>

Converter/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Converter</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Pdf" asp-action="Index" class="navbar-brand">PDF Converter</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    
                    @*<li><a asp-area="" asp-controller="Pdf" asp-action="Index">PDF Converter</a></li>*@
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
           
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>